// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfub1jlDsJOhlZ9MhsfilI9Hzb0MV5FR4',
    appId: '1:714808148376:web:ca000db62e99e649f7ebed',
    messagingSenderId: '714808148376',
    projectId: 'mandoob-c8588',
    authDomain: 'mandoob-c8588.firebaseapp.com',
    storageBucket: 'mandoob-c8588.appspot.com',

    measurementId: 'G-11YHBVD81R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58YewKJmUyNMtvqcV9Nv1TC1Mxw1R0Mw',
    appId: '1:714808148376:android:206a96a264e8ac24f7ebed',
    messagingSenderId: '714808148376',
    projectId: 'mandoob-c8588',
    storageBucket: 'mandoob-c8588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnDcDNRbrksg7ymuU6T8GHsbaoDUw1Wg',
    appId: '1:714808148376:ios:10ceb70bf44410b8f7ebed',
    messagingSenderId: '714808148376',
    projectId: 'mandoob-c8588',
    storageBucket: 'mandoob-c8588.appspot.com',
    iosBundleId: 'com.example.webProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnDcDNRbrksg7ymuU6T8GHsbaoDUw1Wg',
    appId: '1:714808148376:ios:43a37759808a096cf7ebed',
    messagingSenderId: '714808148376',
    projectId: 'mandoob-c8588',
    storageBucket: 'mandoob-c8588.appspot.com',
    iosBundleId: 'com.example.webProject.RunnerTests',
  );
}
